### ISSUE TITLE
Decide Bech32 HRP

### ISSUE THREAD

**Issue by wo01** [KotoDevelopers/koto#1]
We need to change the following variables in chainparams.cpp.
```
bech32HRPs[SAPLING_PAYMENT_ADDRESS]
bech32HRPs[SAPLING_FULL_VIEWING_KEY]
bech32HRPs[SAPLING_INCOMING_VIEWING_KEY]
bech32HRPs[SAPLING_SPENDING_KEY]
```

**Comment by wo01** [comment]
そうですね，アドレスはkotoから始まります

PRすれば登録されるかもしれませんが，SegwitのためではないのでSLIP173に該当するかは
悩ましいところですね．

**Comment by str4d** [comment]
Two notes:

- `SAPLING_SPENDING_KEY` is being replaced by `SAPLING_EXTENDED_SPEND_KEY` in https://github.com/zcash/zcash/pull/3492 (as we are making every Sapling address deterministic from the beginning).
- You'll also need to change the [BIP 44 coin type](https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L85) (once you rebase onto 2.0.0+) to match yours (as registered in SLIP 44).

**Comment by wo01** [comment]
Thanks.
We will modify the above information until Koto 2.0 release.

**Comment by daira** [comment]
Nice to see developers of Zcash forks being proactive about avoiding address conflicts, thanks.
