### ISSUE TITLE
Bump block version

### ISSUE THREAD

**Issue by wo01** [KotoDevelopers/koto#2]
We have to add hashFinalSaplingRoot filed into BlockHeader for Sapling.
Also, we need to change serialization method for PoW.

**Comment by okoto-xyz** [comment]
It seems block header size will be changed from 80 bytes to 112 bytes.
Update is needed for miner as well as pool, right?

**Comment by Harumaki-cryptocoin** [comment]
@okoto-xyz
Right.
Sapling update includes only Official cpuminer-yescrypt also coind.

**Comment by wo01** [comment]
Yes.
We have to update cpuminer.
And also, you need to change multi-hasing module for yescrypt when using k-nomp.

**Comment by wo01** [comment]
その予定ですが，不都合がありましたら変更可能です．

**Comment by okoto-xyz** [comment]
どういうものなのかよくわかってないですが、zcashと違う位置だったので気になりました。
zcashと同じ位置のほうが他のコードでも同じ位置で読みやすい気もしますが、
一番最後に追加したほうが現在のKotoやBTCの仕様に近いしシリアライズ処理しやすそうですかね。
いずれにせよバージョンで分岐処理したりするならどちらでもいいのかもしれません。

**Comment by wo01** [comment]
途中に新しいフィールドを挿入すると，それ以降のフィールドがずれていくので修正箇所が多くなりますので，この位置にしたいと思います．cpuminerは修正が終わり112バイトでマイニングできるようにはなりました．ブロックのversion4と5で処理を切り替えればユーザは意識せずに移行できるかと思います．
