### ISSUE TITLE
Add Qt wallet

### ISSUE THREAD

**Issue by wo01** [KotoDevelopers/koto#3]

**Comment by wo01** [comment]
Source code of Qt wallet have been merged to develop branch.
But, there are some unfinished translations.

**Comment by dragonhuntr** [comment]
What needs translating?

**Comment by wo01** [comment]
We need to update translation files.
https://github.com/KotoDevelopers/koto/tree/develop/src/qt/locale

**Comment by sva-h4cky0** [comment]
@wo01 can you write instructions how to compile Qt wallet from sources for non Ubuntu user please?
